## <center>CSE 546: Reinforcement Learning</center>
### <center>Prof. Alina Vereshchaka</center>
<!-- ### <center>Fall 2022</center> -->

Welcome to the Assignment 2, Part 1: Introduction to Deep Reinforcement Learning and Neural Networks! The goal of this assignment is to make you comfortable with the application of different Neural Network structures depending on how the Reinforcement Learning environment is set up.

In [21]:
# Imports
from environment import WumpusWorldEnvironment

# Environment

We will be working with an implementation of the Wumpus World environment. The environment comes from the book "Artificial Intelligence: A Modern Approach" by Stuart J. Russell and Peter Norvig. 

### ENVIRONMENT DETAILS:

The environment is a 6 x 6 grid world containing a total of 36 grid blocks. 

#### ENVIRONMENT OBJECTS:
The environment consists of the following objects:

1. **Agent** - The agent starts in the grid block at the bottom left corner whose co-ordinates are [0, 0]. The goal of our agent is to collect the Gold while avoiding the Wumpus and the pits. 

2. **Wumpus** - The monster which would eat the agent if they are in the same grid block.

3. **Pit** - The agent must avoid falling into the pits. 

4. **Gold** - The agent must collect the Gold.

5. **Breeze** - Breeze surrounds the Pits and warn the agent of a Pit in an adjacent grid block.

6. **Stench** - Stench surrounds the Wumpus and warns the agent of the Wumpus in an adjacent grid block.

#### ENVIRONMENT OBSERVATIONS:

Our implementation of the environment provides you with four different types of observations:

1. **Integer** - Integer in the range [0 - 35]. This represents the grid block the agent is in. E.g., if the agent is in the bottom left grid block (starting position) the observation would be 0, if the agent is in the grid block containing the Gold the observation would be 34, if the agent is in the top right grid block the observation would be 35.

2. **Vector** - 

    **2.1.** A vector of length 2 representing the agent co-ordinates. The first entry represents the x co-ordinate and the second entry represets the y co-ordinate. E.g., if the agent is in the bottom left grid block (starting position) the observation would be [0, 0], if the agent is in the grid block containing the Gold the observation would be [4, 5], if the agent is in the top right grid block the observation would be [5, 5].
    
    **2.2.** A vector of length 36 representing the one-hot encoding of the integer observation (refer type 1 above). E.g., if the agent is in the bottom left grid block (starting position) the observation would be [1, 0, ..., 0, 0], if the agent is in the grid block containing the Gold the observation would be [0, 0, ..., 1, 0], if the agent is in the top right grid block the observation would be [0, 0, ..., 0, 1].


3. **Image** - Image render of the environment returned as an NumPy array. The image size is 84 * 84 (same size used in the DQN paper). E.g., if the agent is in the bottom right grid block the observation is:

    Observation: (84 * 84)

     [[255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     ...

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]

     [255 255 255 ... 255 255 255]]

    Observation type: <class 'numpy.ndarray'>

    Observation Shape: (84, 84)

    Visually, it looks like:
    <img src="./images/environment_render.png" width="500" height="500">
    

4. **Float** - Float in the range [0 - $\infty$] representing the time elapsed in seconds. 

#### ENVIRONMENT ACTIONS:

Our implementation of the environment provides you with three different types of actions:

1. **Discrete** - Integer in the range [0 - 3] representing the four actions possible in the environment as follows: 0 - Right 1 - Left 2 - Up 3 - Down.

2. **Multi-Discrete** - Array of length four where each element takes binary values 0 or 1. Array elements represent if we take a particular action. Array element with index 0 corresponds to the right action, index 1 corresponds to the left action, index 2 corresponds to the up action, and index 3 corresponds to the down action. E.g., 
   action = [1, 0, 0, 0] would result in the agent moving right.
   action = [1, 0, 1, 0] would result in the agent moving right and up.
   action = [0, 1, 0, 1] would result in the agent moving left and down.

3. **Continuous** - Float in the range [-1, 1] determining whether the agent will go left, right, up, or down as follows:

    if -1 <= action <= -0.5:
        Go Right.
    elif -0.5 < action <= 0:
        Go Left.
    elif 0 < action <= 0.5:
        Go Up.
    elif 0.5 < action <= 1:
        Go Down.
        
### YOUR TASK IS TO USE A NEURAL NETWORK TO WORK WITH ALL FOUR TYPES OF OBSERVATIONS AND ALL THREE TYPES OF  ACTIONS.
### Note: You don't have to train your agent/neural network. You just have to build the neural network structure that takes the observation as input and produces the desired output with the initial weights.

#### You can use libraries such as PyTorch/TensorFlow/Keras to build your neural networks.

#### <span style="color:red">You cannot use RL libraries that already provide the neural network to you such as Stable-baselines3, Keras-RL, TF agents, Ray RLLib etc.</span>

<img src="./images/wumpus_world_environment.jpg" width="600" height="600">

# START COMPLETING YOUR ASSIGNMENT HERE
## Observation Type - Float, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a float (refer to environment observations type 4). The output of the neural network is an array representing the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [142]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
def build_q_network():
    model = models.Sequential()
    model.add(layers.InputLayer(input_shape=(1,)))  #input layer 
    model.add(layers.Dense(64, activation='relu'))   #hidden layer with 64 neurons 
    model.add(layers.Dense(4, activation='linear'))   #output layer for 4 neurons
    model.compile(optimizer='adam', loss='mse')     #compile the model 
    return model
q_model = build_q_network()    #create the q learning model 
observation = np.array([observation]).reshape(-1, 1)  #reshape observation 
q_pred = q_model.predict(observation)   #predict q values 
print(f"Observation (grid position): {observation.flatten()[0]}")
print(f"Predicted Q-values for actions (Right, Left, Up, Down): {q_pred}")
# END_YOUR_CODE

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Observation (grid position): 0
Predicted Q-values for actions (Right, Left, Up, Down): [[0. 0. 0. 0.]]


## Observation Type - Vector (2.1), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 2 (refer to environment observations type 2.1). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_2_64_4.png">

In [148]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='vector', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
def build_model():    #function to create the neural network 
    model = models.Sequential()
    model.add(layers.InputLayer(input_shape=(2,)))  #input layer 
    model.add(layers.Dense(64, activation='relu'))  #hidden layer with 64 neurons
    model.add(layers.Dense(4, activation='linear')) #output layer for 4 neurons
    return model


q_net = build_model()  #create the model 
observation = np.array([2,1]) 
observation = observation.reshape(1, -1)  #reshape observation 
q_pred = q_net.predict(observation)      #predict q values 
print(f"Observation (coordinates): {observation}")
print(f"Predicted Q-values (for actions Right, Left, Up, Down): {q_pred}")
# END_YOUR_CODE

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Observation (coordinates): [[2 1]]
Predicted Q-values (for actions Right, Left, Up, Down): [[ 0.39299312 -0.20845181 -0.45352894 -0.35445794]]


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


## Observation Type - Vector (2.2), Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4.png">

In [154]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
#function to create the q network 
def build_q_network(input_size=36, hidden_units=64, output_size=4):
    model = models.Sequential()
    model.add(layers.InputLayer(input_shape=(input_size,)))  #input layer with 36 neurons 
    model.add(layers.Dense(hidden_units, activation='relu'))  #hidden layer with 64 neurons
    model.add(layers.Dense(output_size, activation='linear'))   #output layer for 4 neurons
    return model

def encode_position(position, size=36):   #function to one hot encode 
    encoded = np.zeros(size)
    encoded[position] = 1  #set position to 1 in one hot encoded
    return encoded
    
agent_position = 0  
one_hot_observation = encode_position(agent_position) #One hot encode the position
q_net = build_q_network() #build the q network 
q_pred = q_net(np.array([one_hot_observation])) 
print("Agent's Position:", agent_position)
print("One-hot Encoded Observation:", one_hot_observation)
print("Predicted Q-values:", q_pred.numpy()) 

# END_YOUR_CODE

Agent's Position: 0
One-hot Encoded Observation: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Q-values: [[ 0.27467504 -0.13080467  0.13010764  0.01595921]]


## Observation Type - Image, Action Type - Discrete

The part of the assignment requires you to create a convolutional neural network with one convolutional layer having 128 filters of size 3 x 3, one hidden layer having 64 neurons, and the output layer having 4 neurons. The input to the neural network is an image of size 84 * 84 (refer to environment observations type 3). The output of the neural network is an array represeting the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/convolutional_neural_network_84x84_128_64_4.png">

In [158]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='image', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import tensorflow as tf
from tensorflow.keras import layers, models

#function to create cnn model 
def build_model():
    model = models.Sequential()
    model.add(layers.Conv2D(128, (3, 3), activation='relu', input_shape=(84, 84, 1))) #conv layer with 128 filters
    model.add(layers.Flatten()) #flattening the output
    model.add(layers.Dense(64, activation='relu')) #dense layer with 64 neurons 
    model.add(layers.Dense(4, activation='linear')) #output layer with 4 neurons 
    return model
model = build_model() #build cnn model 
observation = observation.reshape((1, 84, 84, 1))  #reshape the observation
q_pred = model.predict(observation)  #get the qvalues for the observation
print("Observation:", observation)
print("Predicted Q-values:", q_pred)

# END_YOUR_CODE

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Observation: [[[[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]

  ...

  [[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   ...
   [255]
   [255]
   [255]]]]
Predicted Q-values: [[  1.8396155 -11.850868   14.430632   -1.774659 ]]


## Observation Type - Float, Action Type - Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a float (refer to environment observations type 4). The output of the neural network is an array representing the Q-values from which you will choose an action (refer to environment actions type 1).

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_1_64_4.png">

In [160]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted Q-values for the four actions. Print the observation and the Q-values."""

environment = WumpusWorldEnvironment(observation_type='float', action_type='discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import torch
import torch.nn as nn
import torch.optim as optim

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1, 64)  #input layer with 1 feature
        self.relu = nn.ReLU() #activation func
        self.fc2 = nn.Linear(64, 4)  #output layer with 4 neurons
    def forward(self, x):
        x = self.fc1(x)  #pass through input layer
        x = self.relu(x)  #ReLU activation
        x = self.fc2(x)   #pass through output layer
        return x

net = SimpleNN() #initialize the nn
obs_tensor = torch.tensor([[observation]], dtype=torch.float32)
q_pred = net(obs_tensor)  #predict Q values
print(f"Observation: {observation}")
print(f"Q-values: {q_pred}")
# END_YOUR_CODE

Observation: 0.00013589859008789062
Q-values: tensor([[-0.0470, -0.4100, -0.0401,  0.0703]], grad_fn=<AddmmBackward0>)


## Observation Type - Vector (2.2), Action Type - Multi-Discrete

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 4 neurons. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an array representing the probability of choosing the actions. (If the value of the array element is >=0.5 you will perform the action.) (refer to environment actions type 2).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector.

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_4_sigmoid.png">

In [166]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action probabilities for the four actions. Print the observation and the action probabilities."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='multi_discrete')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

class SimpleNN(nn.Module):  #define neural network 
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(36, 64)  #input layer with 36 neurons 
        self.relu = nn.ReLU()  #activation function
        self.fc2 = nn.Linear(64, 4)  #output layer with 4 neurons
        self.sigmoid = nn.Sigmoid() 

    def forward(self, x):
        x = self.fc1(x)  #pass through input layer 
        x = self.relu(x)  #apply relu activation
        x = self.fc2(x)  #pass through output layer
        x = self.sigmoid(x)  #sigmoid activation 
        return x
        
observation_one_hot = np.zeros(36) #convert observation to one-hot encoding
observation_one_hot[observation] = 1  
obs_tensor = torch.tensor([observation_one_hot], dtype=torch.float32) #convert the one-hot encoded obs to a tensor
net = SimpleNN() #initilize neural network 
action_probs = net(obs_tensor) #get the action probabilities
print(f"One-hot encoded observation: {observation_one_hot}")
print(f"Action probabilities: {action_probs}")


# END_YOUR_CODE

One-hot encoded observation: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Action probabilities: tensor([[0.5446, 0.4792, 0.5041, 0.5383]], grad_fn=<SigmoidBackward0>)


## Observation Type - Vector (2.2), Action Type - Continuous

The part of the assignment requires you to create a sequential dense neural network with 1 hidden layer having 64 neurons and the output layer having 1 neuron. The input to the neural network is a vector of length 36 (refer to environment observations type 2.2). The output of the neural network is an float in the range [-1, 1] determining the action which will be taken. (refer to environment actions type 3).

**HINT:** Use the integer observation and convert it to a one-hot encoded vector and use the TanH activation function to get the output in the range [-1, 1].

The following figure shows the network structure you will have to use:

<img src="./images/neural_network_structures/neural_network_36_64_1.png">

In [175]:
"""TO DO: Create a neural network, pass it the observation from the environment
and get the predicted action. Print the observation and the predicted action."""

environment = WumpusWorldEnvironment(observation_type='integer', action_type='continuous')
observation, info = environment.reset()

# BEGIN_YOUR_CODE
import torch
import torch.nn as nn
import numpy as np

class ContinuousActionNN(nn.Module):   #define neural network 
    def __init__(self):
        super(ContinuousActionNN, self).__init__()
        self.fc1 = nn.Linear(36, 64)  #input layer with 36 neurons
        self.relu = nn.ReLU()        #activation function
        self.fc2 = nn.Linear(64, 1)  #output layer with continuous action 
        self.tanh = nn.Tanh()  #tanh activation to output continuous values
    def forward(self, x):
        x = self.fc1(x)  #pass through input layer 
        x = self.relu(x)   #apply relu activation
        x = self.fc2(x)  #pass through output layer
        x = self.tanh(x)  
        return x

observation_one_hot = np.zeros(36) #convert observation to one-hot encoding
observation_one_hot[observation] = 1  
observation_tensor = torch.tensor([observation_one_hot], dtype=torch.float32)  #convert the one-hot encoded obs to a tensor
net = ContinuousActionNN()   #initilize neural network 
pred_action = net(observation_tensor)  #get the predicted action
print(f"One-hot encoded observation: {observation_one_hot}")
print(f"Predicted action: {pred_action.item()}")


# END_YOUR_CODE

One-hot encoded observation: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted action: 0.1178104504942894
